name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[BUG] <Short description>"
labels: ["bug"]
body:
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, Python version, etc.
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs and Screenshots
      description: Paste any relevant logs or screenshots.
    validations:
      required: false
