name: 💡 Feature Request
description: Suggest an idea for this project
title: "[FEATURE] <Short description>"
labels: ["enhancement"]
body:
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      placeholder: e.g., Add CLI support
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe how you'd like this feature to work.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions you’ve considered?
    validations:
      required: false
