name: C++ Build on Linux

on: [push]  # Trigger the workflow on push events

jobs:
  build:
    runs-on: self-hosted  # Use a self-hosted runner
    container:
      image: ubuntu:latest  # Use the latest Ubuntu container image

    steps:
      - name: Checkout project
        uses: actions/checkout@v4  # Checkout the repository

      - name: Set up environment  # Update package lists and install required packages
        run: |
          apt-get update && apt-get install -y \
          libboost-all-dev \
          libfftw3-dev \
          libhdf5-dev \
          libhdf5-serial-dev \
          build-essential \
          cmake \
          cmake-qt-gui \
          python3-dev \
          libtinyxml-dev \
          libxerces-c-dev

      - name: Generate and Build FERS
        run: |
          mkdir -p build
          cd build
          cmake -S .. -B . \
            -D FERS_LIB_HDF5="/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so" \
            -D FERS_LIB_HDF5_HL="/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.so" \
            -D CMAKE_CXX_FLAGS="-I/usr/include/hdf5/serial/"
          make -j$(nproc)

      - name: Generate and Build Validator
        working-directory: config_validators  # Set working directory to config_validators
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)
