name: C++ Build on Linux

on:
  release:
    types: [published]  # Trigger the workflow on published releases

jobs:
  build:
    runs-on: self-hosted  # Use a self-hosted runner
    container:
      image: ubuntu:latest  # Use the latest Ubuntu container image

    steps:
      - name: Checkout project
        uses: actions/checkout@v4  # Checkout the repository

      - name: Set up environment  # Update package lists and install required packages
        run: |
          apt-get update && apt-get install -y \
          libhdf5-dev \
          libhdf5-serial-dev \
          build-essential \
          cmake \
          cmake-qt-gui \
          libtinyxml-dev \
          libxerces-c-dev \
          lsb-release

      - name: Set up Python  # Install Python 3.11, pip, and venv
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies in virtual environment  # Create venv and install dependencies
        run: |
          python3 -m venv venv
          . ../venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate and Build FERS
        run: |
          mkdir -p build
          cd build
          . ../venv/bin/activate
          cmake -S .. -B . \
            -D Python_EXECUTABLE=$(which python3) \
            -D CMAKE_BUILD_TYPE=Release \
            -D FERS_LIB_HDF5="/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so" \
            -D FERS_LIB_HDF5_HL="/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.so" \
            -D CMAKE_CXX_FLAGS="-I/usr/include/hdf5/serial/"
          make -j$(nproc)

      - name: Prepare FERS for zip
        run: |
          mkdir -p ./toZip
          cp build/src/fers ./toZip/fers

      - name: Generate and Build Validator
        working-directory: config_validators  # Set working directory to config_validators
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Prepare Validator for zip  # Copy the Validator binaries to the zip directory
        run: |
          cp config_validators/build/xml_validator_output ./toZip/xml_validator_output
          cp config_validators/build/kml_visualiser ./toZip/kml_visualiser
          cp config_validators/build/validator ./toZip/validator

      - name: Zip Docs and Build
        uses: TheDoctor0/zip-release@0.7.6  # Use the zip-release action to create a zip archive
        with:
          directory: ./toZip # Directory to add to the archive
          path: ./*
          Filename: FERS.zip # The name of the archive file

      - name: Upload to Release
        uses: softprops/action-gh-release@v1  # Use the action-gh-release action to upload the zip file to the release
        with:
          files: |
            ./toZip/FERS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
